version: '3.3'

services:
  stable-diffusion:
    container_name: 'sd-webui'
    image: 'hlky/sd-webui:runpod'
    volumes:
      - 'outputs:/sd/outputs'
    ports:
      - '8501:8501'
    healthcheck:
      test: 'curl --fail http://localhost:8501 --head || echo 1'
      interval: '30s'
      timeout: '1s'
      retries: 10
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ 'gpu' ]

volumes:
  outputs:
